spring:
  application:
    name: TecheerTreeBackend

  datasource:
    url: jdbc:mysql://localhost:3306/techeertree
    username: root
    password: kjy154969
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
